### ISSUE TITLE
Incorrect min. element.

### ISSUE THREAD

**Issue by iwasaki-kenta** [MauriceGit/skiplist#3]
Tried to use the library just now with string keys that should be lexicographically ordered, though noticed that the minimum value returned was incorrect.

Might there be a preferred way to have arbitrary-length string keys in this case? The keys I'm looking to use are 256-bit strings, so this current solution additionally would fail for my use case.

Test case:

```go
package testbed

import (
	"github.com/MauriceGit/skiplist"
	"math/big"
	"testing"
	"fmt"
)

type WrappedString struct {
	Id string
}

func (w WrappedString) ExtractKey() float64 {
	num := new(big.Int)
	num.SetBytes([]byte(w.Id))

	fmt.Println(w.Id, " ", float64(num.Uint64()))

	return float64(num.Uint64())
}

func (w WrappedString) String() string {
	return w.Id
}

func TestSkiplist(t *testing.T) {
	list := new(skiplist.SkipList)

	ids := []string{"a", "b", "c", "d"}

	for _, id := range ids {
		list.Insert(WrappedString{Id: id})
	}

	t.Log("min: ", list.GetSmallestNode().GetValue())
	t.Log("max: ", list.GetLargestNode().GetValue())
}
```

Log:

```bash
=== RUN   TestSkiplist
a   97
b   98
c   99
d   100
--- PASS: TestSkiplist (0.00s)
    skiplist_test.go:36: min:  b
    skiplist_test.go:37: max:  d
PASS
ok      github.com/iwasaki-kenta/testbed/inmem 0.002s
```

**Comment by MauriceGit** [comment]
Good morning,

thank you for the complete example code, that made it very easy for me to replicate the issue!
The problem here is the way the skiplist itself is created. If you replace it with the direct call to .New(), everything seems to work just fine! 

```go
// replace:
list := new(skiplist.SkipList)
// with:
list := skiplist.New()
```

By calling new() on the type itself, the arrays will be filled with default values instead of being initializied properly.

Best regards,
Maurice
