### ISSUE TITLE
Convert string to float

### ISSUE THREAD

**Issue by recoilme** [MauriceGit/skiplist#4]
Hello
This implementation use float64 as key
I have strings like aaaaaaaaaaab
May you please advice how get float64 from this?

**Comment by recoilme** [comment]
Thanks for your replay @MauriceGit !
Keys must be ordered lexicographically. In my case (and in case of most of  db's - boltdb, badgerdb, goleveldb) i use []byte and universal converter from any type to it:
https://github.com/recoilme/pudge/blob/master/pudge.go#L261

Or take a look on skip list in goleveldb: https://github.com/syndtr/goleveldb/tree/master/leveldb/memdb

Comparator for byte may looks like:
https://github.com/recoilme/pudge/blob/master/pudge_test.go#L393

Float keys use so-processor, may be not comparable (1.3333333 not equal 1.3333333 ) and not working for byte arrays, strings etc. So right now -  it fast but not usable for me. 

I think by speed comparators will be:
- ints
- floats
- strings 
- []byte

More universal - more slow. Strings may store positive right ordered ints too (with bigendian encoding): https://github.com/recoilme/pudge/blob/master/pudge_test.go#L434

**Comment by recoilme** [comment]
My opinion. 
2 errors in design:
- key limited 8 byte 
- next/previous is cycling 
2 errors in tests:
- first element skiped
- wrong Mb/s metric
 Wrong advice(
I try to find more carefully designed skip list(

**Comment by MauriceGit** [comment]
Hello,

I get, that 8byte key limit may not work for everyone or all use-cases.
The cycling is intentional though. It can be checked against and its explicitly mentioned in the Readme and documentation. 

But if you don't mind me asking, where did the test error occured? (do you have the seed and test case??) No tests are failing for me even used in production for several weeks now.

What do you mean by wrong Mb/s metric? 

That's fine, I guess a good starting point are the other libraries used in comparison, good luck.
